version: "3.0"

services:
    front-end:
        image: achan9528/lot-divider-client
        command: npm start
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
    backend:
        image: achan9528/lot-divider-api:${{ github.sha }}
        command: bash -c "python manage.py test"
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
            - DB_ENGINE=${DB_ENGINE}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - CACHE_BACKEND=${CACHE_BACKEND}
            - CACHE_LOCATION=${CACHE_LOCATION}
            - CACHE_OPTIONS_CLIENT=${CACHE_OPTIONS_CLIENT}
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        ports:
            - "8000:8000"
        depends_on:
            - db
            - cache
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
        ports:
            - "5432:5432"
    cache:
        image: redis
        ports:
            - "6379:6379"
        depends_on: 
            - db
    celery-worker:
        image: achan9528/lot-divider-api:latest
        command: celery -A LotDivider worker -l INFO
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
            - DB_ENGINE=${DB_ENGINE}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - CACHE_BACKEND=${CACHE_BACKEND}
            - CACHE_LOCATION=${CACHE_LOCATION}
            - CACHE_OPTIONS_CLIENT=${CACHE_OPTIONS_CLIENT}
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        depends_on:
            - cache
    celery-beat:
        image: achan9528/lot-divider-api:latest
        command: celery -A LotDivider beat
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
            - DB_ENGINE=${DB_ENGINE}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - CACHE_BACKEND=${CACHE_BACKEND}
            - CACHE_LOCATION=${CACHE_LOCATION}
            - CACHE_OPTIONS_CLIENT=${CACHE_OPTIONS_CLIENT}
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        depends_on:
            - celery-worker