# Generated by Django 2.2.4 on 2021-05-02 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(default=uuid.uuid4, max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owners',
            field=models.ManyToManyField(related_name='relatedPortfolios', to='LotDividerAPI.Client'),
        ),
    ]
