# Generated by Django 2.2.4 on 2021-05-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0002_auto_20210502_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
