# Generated by Django 2.2.4 on 2021-05-07 23:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0003_draftportfolio_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('number', models.CharField(default=uuid.uuid4, max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('draftPortfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftAccounts', to='LotDividerAPI.DraftPortfolio')),
            ],
        ),
    ]
