# Generated by Django 2.2.4 on 2021-05-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0004_draftaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftHoldings', to='LotDividerAPI.DraftAccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedDraftHoldings', to='LotDividerAPI.Security')),
            ],
        ),
    ]
