# Generated by Django 2.2.4 on 2021-05-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0006_drafttaxlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accountUsed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatedProposals', to='LotDividerAPI.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='holdingsUsed',
            field=models.ManyToManyField(related_name='relatedProposals', to='LotDividerAPI.Holding'),
        ),
    ]
