# Generated by Django 2.2.4 on 2021-05-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0009_auto_20210519_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityPrice',
        ),
    ]
